### ISSUE TITLE
Observed carbs

### ISSUE THREAD

**Issue by Kalhama** [Kalhama/iob-calculator-nextjs#21]

**Comment by Kalhama** [comment]
Currently works but I don't think this fits for the main screen.

<img width="561" alt="Screenshot 2024-08-22 at 20 49 21" src="https://github.com/user-attachments/assets/890f540a-ec7f-48fc-a166-d1403a8bb525">

**Comment by Kalhama** [comment]
I played also with a cumulative view, but this is not very useful when the integration error becomes too great. Like in the photo ISF was high during the night and low after waking up. Now if these errors had same directionality they would accumulate quite badly. Also y axis resolution dissipates over on high carb loads. 

<img width="425" alt="Screenshot 2024-08-28 at 12 59 38" src="https://github.com/user-attachments/assets/5e9eb9ed-2057-4e37-b898-7731c7631b4f">

I think that best solution is to implement something similar to Loop so observed carbs are always split to corresponding meal entries. 

I played with SQL query to implement this logic and I think it could look something like this. However I am not fan of all the fussing with the timestamps. Maybe I could figure out a smarter way to do this. 

```sql
WITH minutes AS (
  SEELCT generate_series(from, NOW(), interval '1 minutes') AS timestamp
), carb_minimum_absorption_rate AS (
  select 
    minutes.timestamp as timestamp,
    decay,
    value,
    id,
    value / decay / 1.5 as minimium_absorption_rate,
    SUM(value / decay / 1.5) OVER (PARTITION BY timestamp) AS total_minimium_absorption_rate /*if there are multiple meal entries for one timestamp, sum all of their minimum_absorption_rates */
  from minutes
  left join carbs on minutes.timestamp < carbs.timestamp and minutes.timestamp + interval '1 minute' >= carbs.timestamp
) carb_minimum_absorption_rate_observed_carbs AS (
  SELECT 
     timestamp,
     decay,
     value,
     id,
     minimium_absorption_rate,
     total_minimium_absorption_rate,
     minimium_absorption_rate / total_minimium_absorption_rate * (interval '1 minutes' / observed_carbs.interval * observed_carbs.rate) AS observed_carbs
  FROM carb_minimum_absorption_rate
  LEFT JOIN observed_carbs 
    ON observed_carbs.timestamp <= carb_minimum_absorption_rate.timestamp 
    AND (observed_carbs.timestamp + observed_carbs.interval) > carb_minimum_absorption_rate.timestamp /* todo this should add carb.decay * 150% */
)

/* TODO add group by id to get how observed carbs per food */
```

**Comment by Kalhama** [comment]
>Other option from Loop algo would be stacking carbs temporally. If I have just eaten a large meal and I eat more the digestion is just gonna run longer, not higher.
>
>Exception for this would be short carbs that have different pathway thus they do stack.

After thinking about this overnight I think this can be achieved my adding more carbs and decay time to the already existing meal.

**Comment by Kalhama** [comment]
> Perhaps sufficient timestamps would be every time a) carbs start b) end c) NOW(). Only edge case is (that is also prevalent here) when the absorbed_carbs.timestamp (=glucose.timestamp) does not match this series that well. I guess we could counteract this by doing a linear interpolation for generating missing glucose readings.

I continued and played with these ideas at here [#60554d - query_all_metrics_at_any_timeframe.sql](https://github.com/Kalhama/iob-calculator-nextjs/blob/60554d5fe0b2e46edad366a98fd9a8830324ce05/nextjs/query_all_metrics_at_any_timeframe.sql). 

This demonstrates a neat way to calculate `glucose`, `total_carbs_absorbed (predicted)` and `total_insulin_absorbed` for any timeframe. With these we can calculate `total_carbs_absorbed (observed)`. 

Now with these four we can continue on splitting the observed carbs for each meal as we did in the comment above (https://github.com/Kalhama/iob-calculator-nextjs/issues/21#issuecomment-2314912788) but this time with nice timeframe.

**TODO for query_all_metrics_at_any_timeframe.sql**
- [ ] `total_carbs_absorbed` and `total_insulin_absorbed` start from non zero value if first meal/bolus affecting at the start of time started before start of time
- [ ] Add start, end filter to the timeframe
- [ ] Add `NOW()` or `LAST(glucose.timestamp)` to the timeframe
- [ ] consider whether interpolate should return null if interpolated range is too long

**Comment by Kalhama** [comment]
Attributing carbs to meals
- lets have two priority levels for meals depending on whether decay is ongoing or if decay has just ended.
    - primarily attribute all carbs to priority 1 meal(s). 
    - If none exist then attribute carbs to priority 2 meal(s). 
    - If no meals are available do not attribute them to any soecific meal
