### ISSUE TITLE
Refactor SQL queries using SQL functions

### ISSUE THREAD

**Issue by Kalhama** [Kalhama/iob-calculator-nextjs#40]
> Perhaps sufficient timestamps would be every time a) carbs start b) end c) NOW(). Only edge case is (that is also prevalent here) when the absorbed_carbs.timestamp (=glucose.timestamp) does not match this series that well. I guess we could counteract this by doing a linear interpolation for generating missing glucose readings.

I continued and played with these ideas at here [#60554d - query_all_metrics_at_any_timeframe.sql](https://github.com/Kalhama/iob-calculator-nextjs/blob/60554d5fe0b2e46edad366a98fd9a8830324ce05/nextjs/query_all_metrics_at_any_timeframe.sql). 

This demonstrates a neat way to calculate `glucose`, `total_carbs_absorbed (predicted)` and `total_insulin_absorbed` for any timeframe. With these we can calculate `total_carbs_absorbed (observed)`. 

Now with these four we can continue on splitting the observed carbs for each meal as we did in the comment above (https://github.com/Kalhama/iob-calculator-nextjs/issues/21#issuecomment-2314912788) but this time with nice timeframe.

**TODO for query_all_metrics_at_any_timeframe.sql**
- [ ] `total_carbs_absorbed` and `total_insulin_absorbed` start from non zero value if first meal/bolus affecting at the start of time started before start of time
- [ ] Add start, end filter to the timeframe
- [ ] Add `NOW()` or `LAST(glucose.timestamp)` to the timeframe
- [ ] consider whether interpolate should return null if interpolated range is too long

_Originally posted by @Kalhama in https://github.com/Kalhama/iob-calculator-nextjs/issues/21#issuecomment-2317778863_
